# Imagem base do Node.js
FROM node:18

# Diretório de trabalho no container
WORKDIR /app

# Copia os arquivos package.json e package-lock.json
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos da aplicação
COPY . .

# Expõe a porta configurada no .env
EXPOSE 3333

# Comando para iniciar a aplicação
CMD ["node", "src/index.js"]
