services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - AUTH_MS_URL=http://auth-service:8081
      - PACIENTE_MS_URL=http://paciente-service:8082
      - CONSULTA_MS_URL=http://consulta-service:8083
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - auth-service
      - paciente-service
    networks:
      - hospital-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - auth-db
    networks:
      - hospital-network

  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - hospital-network

  paciente-service:
    build: ./paciente-service
    container_name: paciente-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://paciente-db:5432/pacientedb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET=${STRIPE_SECRET}
    env_file:
      - .env
    depends_on:
      - auth-service
      - paciente-db
    networks:
      - hospital-network

  paciente-db:
    image: postgres:17
    container_name: paciente-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pacientedb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - paciente-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - hospital-network

  consulta-service:
    build: ./consulta-service
    container_name: consulta-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://consulta-db:5432/consultadb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    depends_on:
      - consulta-db
    networks:
      - hospital-network

  consulta-db:
    image: postgres:17
    container_name: consulta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: consultadb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - consulta-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - hospital-network

  pgadmin:
    image: dpage/pgadmin4
    user: "root"
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - hospital-network

  front-end:
    build: ./front-end
    container_name: front-end
    restart: unless-stopped
    ports:
      - "88:88"
    networks:
      - hospital-network
    depends_on:
      - api-gateway
      - auth-service
      - paciente-service
      - consulta-service

volumes:
  auth-data:
  paciente-data:
  consulta-data:

networks:
  hospital-network:
    driver: bridge
